### ISSUE TITLE
Adding users to GitHub widget

### ISSUE THREAD

**Issue by scottsweb** [Automattic/vip-dashboard#53]
Our minimum is to add a form to the dashboard to request collaborator access on GitHub. This should look and function like Zendesk ticket form... in fact I am guessing it will generate a Zendesk ticket so this can be actioned manually. 

Further down the road we’ll need some kind of mass user management, possibly by converting the VIP Go concept of clients to organisations and allowing many organisations to be associated with a single site… but possibly not. At this point the widget can be removed.

**Comment by mdrovdahl** [comment]
Hi, I am a lonely ticket. Won't somebody love me?

Also, when you're ready to do this...please look at the existing function [here](https://opengrok.a8c.com/source/xref/trunk/wp-content/admin-plugins/wpcom-vip/dashboard-widgets/widget-request-svn-access.php#97) and be sure to do the Salesforce integration as that is where Growth can/will reconcile support seats.

**Comment by scottsweb** [comment]
Noted, bumping up my list

**Comment by scottsweb** [comment]
Closing as we look to automate this in other ways.
