### ISSUE TITLE
Ticket priority for ZD tickets is not set correctly.

### ISSUE THREAD

**Issue by scottsweb** [Automattic/vip-dashboard#57]
> when you submit a ticket through the VIP Dashboard for VIP Go sites, the ticket priority does not get properly set. When they submitted a “high” priority ticket, it turns up as “normal” in our queue. This was tested and confirmed.

**Comment by stephyiu** [comment]
@scottsweb we just received a report that this is not working, in #54785.

**Comment by scottsweb** [comment]
@stephyiu Thanks. I will check to make sure the fix was deployed. This is open again now to track it.

**Comment by scottsweb** [comment]
@stephyiu The fix has not made it to production yet, apologies.

**Comment by ethitter** [comment]
@stephyiu @scottsweb - this is now deployed.
