### ISSUE TITLE
VIP Go-centric Welcome widget

### ISSUE THREAD

**Issue by mripka** [Automattic/vip-dashboard#59]
Is this were I would request the VIP Go sites to have a Go-focused Welcome to VIP widget? 

Referring to 
https://cldup.com/w41-y16S7Q.png

Links to update for Go sites:
"VIP Go Documentation" -> https://vip.wordpress.com/documentation/vip-go/

"VIP Plugins" - unsure, I'm still thinking on this and "Plugins" link in black bar

"Launch Checklist" -> https://vip.wordpress.com/documentation/vip-go/launch-checklist/

"Your VIP Toolbox" rename to "Accessing VIP Support" -> https://vip.wordpress.com/vip-go-toolbox/ (not yet published)

**Comment by scottsweb** [comment]
Thanks for this @mripka, I will take a look at getting these updated 👍
