### ISSUE TITLE
Filter the 'from' address when sending support requests from dashboard

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-dashboard#62]
WP 4.6 made some changes to the underlying email handling, which necessitated this change:

https://github.com/Automattic/vip-go-mu-plugins/pull/277

The need for that will go away in 4.6.1 (we can set `Sender` again), but in the meantime, we're sending emails from the wrong address when creating tickets from the dashboard.

Instead, we should be using `vip-support@wordpress.com `, which we set via a header...but with the `wp_mail_from` filter, the header is overridden, which breaks it. 

So temporarily, we should filter `wp_mail_from` here, and remove the filter after sending is complete.

**Comment by scottsweb** [comment]
We need to set the FROM address to the user requesting support and make sure this makes it way to Zendesk, the filters implemented above do not seem to be working. Check and re-check.
