### ISSUE TITLE
Browser-specific error on Domains panel

### ISSUE THREAD

**Issue by yolih** [Automattic/vip-dashboard#94]
When trying to add a new domain in the App dashboard (https://dashboard.wpvip.com/apps/{site_id}/domains/production) in the Firefox browser, the browser stops accepting new characters and freezes. 

This occurred with multiple
- Site IDs
- character counts

**How to reproduce:**
- Open Firefox (my version is 72.0.1)
- Navigate to the [Domain panel](https://dashboard.wpvip.com/apps/2086/domains/production) on the App Dashboard
- Click on plus sign to add domain
- Begin typing a string of characters into the text field to the left of the "Add Domain" button

This issue seems specific to Firefox and did not occur on Chrome or Safari.

103632-zen

**Comment by yolih** [comment]
An update that the client who reported this issue is using Chrome Version 79.0.3945.117 which is the same version I am using without experiencing the error. They did not include their OS, just Chrome version.

**Comment by petervibert** [comment]
@yolih per @simonwheatley ([Slack](https://a8c.slack.com/archives/C03CU7X3U/p1582112369348700)) this should be reported in BB8.

**Comment by simonwheatley** [comment]
I copied it over. 

N.B. This repo is the code for the MC admin console, not the client dashboard 😬
